export const antifoulOptions=[
    {brand:"Hempel",name:"Dark Blue",hex:"#012c57",cssVar:"--hempel-antifoul-dark_blue"},
    {brand:"Hempel",name:"Grey",hex:"#716f77",cssVar:"--hempel-antifoul-grey"},
    {brand:"Hempel",name:"True Blue",hex:"#07327a",cssVar:"--hempel-antifoul-true_blue"},
    {brand:"Hempel",name:"Red",hex:"#b60739",cssVar:"--hempel-antifoul-red"},
    {brand:"Hempel",name:"Green",hex:"#018267",cssVar:"--hempel-antifoul-green"},
    {brand:"Hempel",name:"Black",hex:"#011322",cssVar:"--hempel-antifoul-black"},
    {brand:"Hempel",name:"Souvenir Blue",hex:"#0079be",cssVar:"--hempel-antifoul-souvenir_blue"},
    {brand:"International",name:"Black",hex:"#4d4c51",cssVar:"--international-antifoul-black"},
    {brand:"International",name:"Navy",hex:"#365082",cssVar:"--international-antifoul-navy"},
    {brand:"International",name:"Blue",hex:"#2698c2",cssVar:"--international-antifoul-blue"},
    {brand:"International",name:"Green",hex:"#0fa796",cssVar:"--international-antifoul-green"},
    {brand:"International",name:"Red",hex:"#be3e4c",cssVar:"--international-antifoul-red"},
    {brand:"International",name:"Dover White",hex:"#cececd",cssVar:"--international-antifoul-dover_white"},
    {brand:"Seajet",name:"Black",hex:"#272324",cssVar:"--seajet-antifoul-black"},
    {brand:"Seajet",name:"Dark Grey",hex:"#4f5054",cssVar:"--seajet-antifoul-dark_grey"},
    {brand:"Seajet",name:"Mid Blue",hex:"#00567a",cssVar:"--seajet-antifoul-mid_blue"},
    {brand:"Seajet",name:"Navy Blue",hex:"#003051",cssVar:"--seajet-antifoul-navy_blue"},
    {brand:"Seajet",name:"Red",hex:"#b00537",cssVar:"--seajet-antifoul-red"},
  ];